version: '3.8'
services:
  accounts:
    container_name: accounts_app
    image: account_app
    build: ./
    command: ./wait-for-postgres.sh db ./accounts
    environment:
      - "PASSWORD=postgres"
    ports:
      - "8002:8002"
    depends_on:
      - db
    networks:
      - accounts-network

  db:
    restart: always
    image: postgres
    container_name: account_db
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=account_service"
    ports:
      - 5436:5432
    networks:
      - accounts-network

  account-migrator:
    image: account_app
    environment:
      - "PASSWORD=postgres"
    volumes:
      - .:/schema
    command: ["./wait-for-postgres.sh", "db", "--","make","migrate","up"]
    depends_on:
      - db
    networks:
      - accounts-network

networks:
  accounts-network:
    external: false
    name: accounts-network